# Generated by Django 4.2 on 2024-05-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inmobiliaria", "0007_alter_inmueble_comuna"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="comuna",
            field=models.CharField(max_length=50),
        ),
    ]
