# Generated by Django 4.2 on 2024-05-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inmobiliaria", "0013_alter_inmueble_comuna"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudarriendo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("aceptado", "Aceptado"),
                    ("rechazado", "Rechazado"),
                ],
                default="pendiente",
            ),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="propietario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inmobiliaria.usuario"
            ),
        ),
    ]
